Weapons = {
    ['WEAPON_SWITCHBLADE'] = {
        name = 'Briceag',
        hash = 'WEAPON_SWITCHBLADE',
        weight = 1.0,
        ammo = 'ammo-WEAPON_SWITCHBLADE',
        description = 'Briceag',
        type = 'weapons',
    },
    ['WEAPON_NIGHTSTICK'] = {
        name = 'Bulan',
        hash = 'WEAPON_NIGHTSTICK',
        weight = 1.0,
        ammo = 'ammo-WEAPON_NIGHTSTICK',
        description = 'Bulan',
        type = 'weapons',
    },
    ['WEAPON_FIREEXTINGUISHER'] = {
        name = 'Extinctor',
        hash = 'WEAPON_FIREEXTINGUISHER',
        weight = 1.0,
        ammo = 'ammo-WEAPON_FIREEXTINGUISHER',
        description = 'Extinctor',
        type = 'weapons',
    },
    ['WEAPON_FLASHLIGHT'] = {
        name = 'Lanterna',
        hash = 'WEAPON_FLASHLIGHT',
        weight = 1.0,
        ammo = 'ammo-WEAPON_FLASHLIGHT',
        description = 'Lanterna',
        type = 'weapons',
    },
    ['WEAPON_DAGGER'] = {
        name = 'Cutit Dagger',
        hash = 'WEAPON_DAGGER',
        weight = 1.0,
        ammo = 'ammo-WEAPON_DAGGER',
        description = 'Cutit Dagger',
        type = 'weapons',
    },
    ['WEAPON_BAT'] = {
        name = 'Bata',
        hash = 'WEAPON_BAT',
        weight = 1.0,
        ammo = 'ammo-WEAPON_BAT',
        description = 'Bata',
        type = 'weapons',
    },
    ['WEAPON_STUNGUN'] = {
        name = 'Tazer',
        hash = 'WEAPON_STUNGUN',
        weight = 1.0,
        ammo = 'ammo-WEAPON_STUNGUN',
        description = 'Tazer',
        type = 'weapons',
    },
    ['WEAPON_KNUCKLE'] = {
        name = 'Pumnal',
        hash = 'WEAPON_KNUCKLE',
        weight = 1.0,
        ammo = 'ammo-WEAPON_KNUCKLE',
        description = 'Pumnal',
        type = 'weapons',
    },
    ['WEAPON_KNIFE'] = {
        name = 'Cutit',
        hash = 'WEAPON_KNIFE',
        weight = 1.0,
        ammo = 'ammo-WEAPON_KNIFE',
        description = 'Cutit',
        type = 'weapons',
    },
    ['WEAPON_BATTLEAXE'] = {
        name = 'Topor',
        hash = 'WEAPON_BATTLEAXE',
        weight = 1.0,
        ammo = 'ammo-WEAPON_BATTLEAXE',
        description = 'Topor',
        type = 'weapons',
    },
    ['WEAPON_BOTTLE'] = {
        name = 'Sticla Sparta',
        hash = 'WEAPON_BOTTLE',
        weight = 1.0,
        ammo = 'ammo-WEAPON_BOTTLE',
        description = 'Sticla Sparta',
        type = 'weapons',
    },
    ['WEAPON_WRENCH'] = {
        name = 'Cheie Franceza',
        hash = 'WEAPON_WRENCH',
        weight = 1.0,
        ammo = 'ammo-WEAPON_WRENCH',
        description = 'Cheie Franceza',
        type = 'weapons',
    },
    ['WEAPON_MOLOTOV'] = {
        name = 'Molotov',
        hash = 'WEAPON_MOLOTOV',
        weight = 1.0,
        ammo = 'ammo-WEAPON_MOLOTOV',
        description = 'Molotov',
        type = 'weapons',
    },
    ['WEAPON_GRENADE'] = {
        name = 'Grenada',
        hash = 'WEAPON_GRENADE',
        weight = 1.0,
        ammo = 'ammo-WEAPON_GRENADE',
        description = 'Grenada',
        type = 'weapons',
    },
    ['WEAPON_BZGAS'] = {
        name = 'BZ Gas',
        hash = 'WEAPON_BZGAS',
        weight = 1.0,
        ammo = 'ammo-WEAPON_BZGAS',
        description = 'BZ Gas',
        type = 'weapons',
    },
    ['WEAPON_ASSAULTRIFLE'] = {
        name = 'AK-47',
        hash = 'WEAPON_ASSAULTRIFLE',
        weight = 1.0,
        ammo = 'ammo-rifle',
        description = 'AK-47',
        type = 'weapons',
    },
    ['WEAPON_ASSAULTRIFLE_MK2'] = {
        name = 'AK-47 MK2',
        hash = 'WEAPON_ASSAULTRIFLE_MK2',
        weight = 1.0,
        ammo = 'ammo-rifle',
        description = 'AK-47 MK2',
        type = 'weapons',
    },
    ['WEAPON_MG'] = {
        name = 'MG',
        hash = 'WEAPON_MG',
        weight = 1.0,
        ammo = 'ammo-rifle',
        description = 'MG',
        type = 'weapons',
    },
    ['WEAPON_DOUBLEACTION'] = {
        name = 'Double Action',
        hash = 'WEAPON_DOUBLEACTION',
        weight = 1.0,
        ammo = 'ammo-pistol',
        description = 'Double Action',
        type = 'weapons',
    },
    ['WEAPON_GUSENBERG'] = {
        name = 'Gusenberg',
        hash = 'WEAPON_GUSENBERG',
        weight = 1.0,
        ammo = 'ammo-rifle',
        description = 'Gusenberg',
        type = 'weapons',
    },
    ['WEAPON_SAWNOFFSHOTGUN'] = {
        name = 'Sawn Off Shotgun',
        hash = 'WEAPON_SAWNOFFSHOTGUN',
        weight = 1.0,
        ammo = 'ammo-WEAPON_SAWNOFFSHOTGUN',
        description = 'Sawn Off Shotgun',
        type = 'weapons',
    },
    ['WEAPON_HEAVYRIFLE'] = {
        name = 'Heavy Rifle',
        hash = 'WEAPON_HEAVYRIFLE',
        weight = 1.0,
        ammo = 'ammo-rifle',
        description = 'Heavy Rifle',
        type = 'weapons',
    },
    ['WEAPON_MICROSMG'] = {
        name = 'Micro SMG',
        hash = 'WEAPON_MICROSMG',
        weight = 1.0,
        ammo = 'ammo-rifle',
        description = 'Micro SMG',
        type = 'weapons',
    },
    ['WEAPON_COMBATPISTOL'] = {
        name = 'Combat Pistol',
        hash = 'WEAPON_COMBATPISTOL',
        weight = 1.0,
        ammo = 'ammo-pistol',
        description = 'Combat Pistol',
        type = 'weapons',
    },
    ['WEAPON_PISTOL_MK2'] = {
        name = 'Pistol mK2',
        hash = 'WEAPON_PISTOL_MK2',
        weight = 1.0,
        ammo = 'ammo-pistol',
        description = 'Pistol MK2',
        type = 'weapons',
    },
    ['WEAPON_PISTOL50'] = {
        name = 'Pistol 50',
        hash = 'WEAPON_PISTOL50',
        weight = 1.0,
        ammo = 'ammo-pistol',
        description = 'Pistol 50',
        type = 'weapons',
    },
    ['WEAPON_NAVYREVOLVER'] = {
        name = 'Navy Revolver',
        hash = 'WEAPON_NAVYREVOLVER',
        weight = 1.0,
        ammo = 'ammo-pistol',
        description = 'Navy Revolver',
        type = 'weapons',
    },
    ['WEAPON_APPISTOL'] = {
        name = 'AP Pistol',
        hash = 'WEAPON_APPISTOL',
        weight = 1.0,
        ammo = 'ammo-pistol',
        description = 'AP Pistol',
        type = 'weapons',
    },
    ['WEAPON_VINTAGEPISTOL'] = {
        name = 'Vintage Pistol',
        hash = 'WEAPON_VINTAGEPISTOL',
        weight = 1.0,
        ammo = 'ammo-pistol',
        description = 'Vintage Pistol',
        type = 'weapons',
    },
    ['WEAPON_GADGETPISTOL'] = {
        name = 'Gadget Pistol',
        hash = 'WEAPON_GADGETPISTOL',
        weight = 1.0,
        ammo = 'ammo-pistol',
        description = 'Gadget Pistol',
        type = 'weapons',
    },
    ['WEAPON_MACHINEPISTOL'] = {
        name = 'Machine Pistol',
        hash = 'WEAPON_MACHINEPISTOL',
        weight = 1.0,
        ammo = 'ammo-pistol',
        description = 'Machine Pistol',
        type = 'weapons',
    },
    ['WEAPON_HEAVYPISTOL'] = {
        name = 'Heavy Pistol',
        hash = 'WEAPON_HEAVYPISTOL',
        weight = 1.0,
        ammo = 'ammo-pistol',
        description = 'Heavy Pistol',
        type = 'weapons',
    },
    ['WEAPON_ADVANCEDRIFLE'] = {
        name = 'Advanced Rifle',
        hash = 'WEAPON_ADVANCEDRIFLE',
        weight = 1.0,
        ammo = 'ammo-rifle',
        description = 'Advanced Rifle',
        type = 'weapons',
    },
    ['WEAPON_SMG'] = {
        name = 'SMG',
        hash = 'WEAPON_SMG',
        weight = 1.0,
        ammo = 'ammo-rifle',
        description = 'SMG',
        type = 'weapons',
    },
    ['WEAPON_MINISMG'] = {
        name = 'Mini SMG',
        hash = 'WEAPON_MINISMG',
        weight = 1.0,
        ammo = 'ammo-rifle',
        description = 'Mini SMG',
        type = 'weapons',
    },
    ['WEAPON_MINIGUN'] = {
        name = 'Minigun',
        hash = 'WEAPON_MINIGUN',
        weight = 1.0,
        ammo = 'ammo-rifle',
        description = 'Minigun',
        type = 'weapons',
    },
    ['WEAPON_PUMPSHOTGUN'] = {
        name = 'Pump Shotgun',
        hash = 'WEAPON_PUMPSHOTGUN',
        weight = 1.0,
        ammo = 'ammo-rifle',
        description = 'Pump Shotgun',
        type = 'weapons',
    },
    ['WEAPON_PUMPSHOTGUN_MK2'] = {
        name = 'Pump Shotgun MK2',
        hash = 'WEAPON_PUMPSHOTGUN_MK2',
        weight = 1.0,
        ammo = 'ammo-WEAPON_PUMPSHOTGUN_MK2',
        description = 'Pump Shotgun MK2',
        type = 'weapons',
    },
    ['WEAPON_CARBINERIFLE'] = {
        name = 'Caribine Rifle',
        hash = 'WEAPON_CARBINERIFLE',
        weight = 1.0,
        ammo = 'ammo-rifle',
        description = 'Caribine Rifle',
        type = 'weapons',
    },
    ['WEAPON_SPECIALCARBINE'] = {
        name = 'Special Carbine Rifle',
        hash = 'WEAPON_SPECIALCARBINE',
        weight = 1.0,
        ammo = 'ammo-rifle',
        description = 'Special Carbine Rifle',
        type = 'weapons',
    },
    ['WEAPON_CARBINERIFLE_MK2'] = {
        name = 'Caribine Rifle MK2',
        hash = 'WEAPON_CARBINERIFLE_MK2',
        weight = 1.0,
        ammo = 'ammo-rifle',
        description = 'Caribine Rifle MK2',
        type = 'weapons',
    },
    ['WEAPON_MARKSMANRIFLE'] = {
        name = 'Marksman Rifle',
        hash = 'WEAPON_MARKSMANRIFLE',
        weight = 1.0,
        ammo = 'ammo-rifle',
        description = 'Marksman Rifle',
        type = 'weapons',
    },
    ['WEAPON_MARKSMANRIFLE_MK2'] = {
        name = 'Marksman Rifle',
        hash = 'WEAPON_MARKSMANRIFLE_MK2',
        weight = 1.0,
        ammo = 'ammo-rifle',
        description = 'Marksman Rifle',
        type = 'weapons',
    },
    ['WEAPON_HEAVYSNIPER_MK2'] = {
        name = 'Heaby Sniper Rifle',
        hash = 'WEAPON_HEAVYSNIPER_MK2',
        weight = 1.0,
        ammo = 'ammo-rifle',
        description = 'Sniper Rifle',
        type = 'weapons',
    },
    ['WEAPON_RPG'] = {
        name = 'RPG',
        hash = 'WEAPON_RPG',
        weight = 1.0,
        ammo = 'ammo-WEAPON_RPG',
        description = 'RPG',
        type = 'weapons',
    },
    ['WEAPON_GRENADELAUNCHER'] = {
        name = 'Grenade Launcher',
        hash = 'WEAPON_GRENADELAUNCHER',
        weight = 1.0,
        ammo = 'ammo-WEAPON_GRENADELAUNCHER',
        description = 'Grenade Launcher',
        type = 'weapons',
    },
    ['WEAPON_REVOLVER'] = {
        name = 'Revolver',
        hash = 'WEAPON_REVOLVER',
        weight = 1.0,
        ammo = 'ammo-pistol',
        description = 'Revolver',
        type = 'weapons',
    },
    ['WEAPON_REVOLVER_MK2'] = {
        name = 'Revolver MK2',
        hash = 'WEAPON_REVOLVER_MK2',
        weight = 1.0,
        ammo = 'ammo-pistol',
        description = 'Revolver MK2',
        type = 'weapons',
    },
    ['WEAPON_SNSPISTOL'] = {
        name = 'SNS Pistol',
        hash = 'WEAPON_SNSPISTOL',
        weight = 1.0,
        ammo = 'ammo-pistol',
        description = 'SNS Pistol',
        type = 'weapons',
    },
    ['WEAPON_FLAREGUN'] = {
        name = 'Radar Pistol',
        hash = 'WEAPON_FLAREGUN',
        weight = 1.0,
        ammo = 'ammo-shotgun',
        description = 'Pistol Radar',
        type = 'weapons',
    },

}


WeaponsComponents = {
    ["WEAPON_PISTOL_MK2"] = {
        supressor = "COMPONENT_AT_PI_SUPP_02",
        clip = "COMPONENT_PISTOL_MK2_CLIP_02",
        flash = "COMPONENT_AT_PI_FLSH_03",
        scope = "COMPONENT_AT_PI_RAIL_02",
        skin = "COMPONENT_PISTOL_MK2_CAMO_04",
    },
    ["WEAPON_PISTOL"] = {
        supressor = "COMPONENT_AT_PI_SUPP_02",
        clip = "COMPONENT_PISTOL_CLIP_02",
        flash = "COMPONENT_AT_PI_FLSH",
        skin = "COMPONENT_PISTOL_VARMOD_LUXE",
    },
    ["WEAPON_COMBATPISTOL"] = {
        supressor = "COMPONENT_AT_PI_SUPP",
        clip = "COMPONENT_COMBATPISTOL_CLIP_02",
        flash = "COMPONENT_AT_PI_FLSH",
        skin = "COMPONENT_COMBATPISTOL_VARMOD_LOWRIDER",
    },
    ["WEAPON_APPISTOL"] = {
        supressor = "COMPONENT_AT_PI_SUPP",
        clip = "COMPONENT_APPISTOL_CLIP_02",
        flash = "COMPONENT_AT_PI_FLSH",
        skin = "COMPONENT_APPISTOL_VARMOD_LUXE",
    },
    ["WEAPON_MACHINEPISTOL"] = {
        supressor = "COMPONENT_AT_PI_SUPP",
        clip = "COMPONENT_MACHINEPISTOL_CLIP_03",
    },
    ["WEAPON_PISTOL50"] = {
        supressor = "COMPONENT_AT_AR_SUPP_02",
        clip = "COMPONENT_PISTOL50_CLIP_02",
        flash = "COMPONENT_AT_PI_FLSH",
        skin = "COMPONENT_PISTOL50_VARMOD_LUXE",
    },
    ["WEAPON_SNSPISTOL"] = {
        clip = "COMPONENT_SNSPISTOL_CLIP_02",
        skin = "COMPONENT_SNSPISTOL_VARMOD_LOWRIDER",
    },
    ["WEAPON_SNSPISTOL_MK2"] = {
        supressor = "COMPONENT_AT_PI_SUPP_02",
        clip = "COMPONENT_SNSPISTOL_MK2_CLIP_02",
        flash = "COMPONENT_AT_PI_FLSH_03",
        skin = "COMPONENT_SNSPISTOL_MK2_CAMO_04",
    },
    ["WEAPON_HEAVYPISTOL"] = {
        supressor = "COMPONENT_AT_PI_SUPP",
        clip = "COMPONENT_HEAVYPISTOL_CLIP_02",
        flash = "COMPONENT_AT_PI_FLSH",
        skin = "COMPONENT_HEAVYPISTOL_VARMOD_LUXE",
    },
    ["WEAPON_VINTAGEPISTOL"] = {
        supressor = "COMPONENT_AT_PI_SUPP",
        clip = "COMPONENT_VINTAGEPISTOL_CLIP_02",
    },
    ["WEAPON_ASSAULTSMG"] = {
        supressor = "COMPONENT_AT_AR_SUPP_02",
        clip = "COMPONENT_ASSAULTSMG_CLIP_02",
        flash = "COMPONENT_AT_AR_FLSH",
        scope = "COMPONENT_AT_SCOPE_MACRO",
        skin = "COMPONENT_ASSAULTSMG_VARMOD_LOWRIDER",
    },
    ["WEAPON_ASSAULTRIFLE"] = {
        supressor = "COMPONENT_AT_AR_SUPP_02",
        clip = "COMPONENT_ASSAULTRIFLE_CLIP_03",
        flash = "COMPONENT_AT_AR_FLSH",
        scope = "COMPONENT_AT_SCOPE_MACRO",
        skin = "COMPONENT_ASSAULTRIFLE_VARMOD_LUXE",
        grip = "COMPONENT_AT_AR_AFGRIP",
    },
    ["WEAPON_MICROSMG"] = {
        supressor = "COMPONENT_AT_AR_SUPP_02",
        clip = "COMPONENT_MICROSMG_CLIP_02",
        flash = "COMPONENT_AT_PI_FLSH",
        scope = "COMPONENT_AT_SCOPE_MACRO",
        skin = "COMPONENT_MICROSMG_VARMOD_LUXE",
    },
    ["WEAPON_SMG"] = {
        supressor = "COMPONENT_AT_PI_SUPP",
        clip = "COMPONENT_SMG_CLIP_03",
        flash = "COMPONENT_AT_AR_FLSH",
        scope = "COMPONENT_AT_SCOPE_MACRO_02",
        skin = "COMPONENT_SMG_VARMOD_LUXE",
    },
    ["WEAPON_SMG_MK2"] = {
        supressor = "COMPONENT_AT_PI_SUPP",
        clip = "COMPONENT_SMG_MK2_CLIP_02",
        flash = "COMPONENT_AT_AR_FLSH",
        scope = "COMPONENT_AT_SCOPE_SMALL_SMG_MK2",
        skin = "COMPONENT_SMG_MK2_CAMO_04",
    },
    ["WEAPON_CARBINERIFLE"] = {
        supressor = "COMPONENT_AT_AR_SUPP",
        clip = "COMPONENT_CARBINERIFLE_CLIP_03",
        flash = "COMPONENT_AT_AR_FLSH",
        scope = "COMPONENT_AT_SCOPE_MEDIUM",
        skin = "COMPONENT_CARBINERIFLE_VARMOD_LUXE",
        grip = "COMPONENT_AT_AR_AFGRIP",
    },
    ["WEAPON_SPECIALCARBINE"] = {
        supressor = "COMPONENT_AT_AR_SUPP_02",
        clip = "COMPONENT_SPECIALCARBINE_CLIP_03",
        flsh = "COMPONENT_AT_AR_FLSH",
        scope = "COMPONENT_AT_SCOPE_MEDIUM",
        skin = "COMPONENT_SPECIALCARBINE_VARMOD_LOWRIDER",
        grip = "COMPONENT_AT_AR_AFGRIP",
    },
    ["WEAPON_SPECIALCARBINE_MK2"] = {
        supressor = "COMPONENT_AT_AR_SUPP_02",
        clip = "COMPONENT_SPECIALCARBINE_MK2_CLIP_02",
        flash = "COMPONENT_AT_AR_FLSH",
        scope = "COMPONENT_AT_SCOPE_MEDIUM_MK2",
        skin = "COMPONENT_SPECIALCARBINE_MK2_CAMO_10",
        grip = "COMPONENT_AT_AR_AFGRIP_02",
    },
    ["WEAPON_COMPACTRIFLE"] = {
        clip = "COMPONENT_COMPACTRIFLE_CLIP_02",
    },
    ["WEAPON_BULLPUPRIFLE_MK2"] = {
        supressor = "COMPONENT_AT_AR_SUPP",
        clip = "COMPONENT_BULLPUPRIFLE_MK2_CLIP_02",
        flash = "COMPONENT_AT_AR_FLSH",
        scope = "COMPONENT_AT_SCOPE_SMALL_MK2",
        skin = "COMPONENT_BULLPUPRIFLE_MK2_CAMO_10",
        grip = "COMPONENT_AT_AR_AFGRIP_02",
    },
    ["WEAPON_MILITARYRIFLE"] = {
        supressor = "COMPONENT_AT_AR_SUPP",
        clip = "COMPONENT_MILITARYRIFLE_CLIP_02",
        flash = "COMPONENT_AT_AR_FLSH",
        scope = "COMPONENT_AT_SCOPE_SMAL",
        skin = "COMPONENT_MILITARYRIFLE_SIGHT_01",
    },
    ["WEAPON_ASSAULTRIFLE_MK2"] = {
        supressor = "COMPONENT_AT_AR_SUPP_02",
        clip = "COMPONENT_ASSAULTRIFLE_MK2_CLIP_02",
        flash = "COMPONENT_AT_AR_FLSH",
        scope = "COMPONENT_AT_SCOPE_MACRO",
        skin = "COMPONENT_ASSAULTRIFLE_VARMOD_LUXE",
        grip = "COMPONENT_AT_AR_AFGRIP",
    },
    ["WEAPON_MG"] = {
        clip = "COMPONENT_MG_CLIP_02",
        scope = "COMPONENT_AT_SCOPE_SMALL_02",
        skin = "COMPONENT_MG_VARMOD_LOWRIDER",
    },
    ["WEAPON_COMBATMG"] = {
        clip = "COMPONENT_COMBATMG_MK2_CLIP_02",
        scope = "COMPONENT_AT_SCOPE_MEDIUM_MK2",
        skin = "COMPONENT_COMBATMG_MK2_CAMO_04",
        grip = "COMPONENT_AT_AR_AFGRIP_02",
    },
    ["WEAPON_GUSENBERG"] = {
        clip = "COMPONENT_GUSENBERG_CLIP_02",
    },
    ["WEAPON_PUMPSHOTGUN"] = {
        supressor = "COMPONENT_AT_SR_SUPP",
        flash = "COMPONENT_AT_AR_FLSH",
        skin = "COMPONENT_PUMPSHOTGUN_VARMOD_LOWRIDER",
    },
    ["WEAPON_SAWNOFFSHOTGUN"] = {
        skin = "COMPONENT_SAWNOFFSHOTGUN_VARMOD_LUXE",
    },
    ["WEAPON_ASSAULTSHOTGUN"] = {
        supressor = "COMPONENT_AT_AR_SUPP",
        clip = "COMPONENT_ASSAULTSHOTGUN_CLIP_02",
        flash = "COMPONENT_AT_AR_FLSH",
        grip = "COMPONENT_AT_AR_AFGRIP",
    },
    ["WEAPON_BULLPUPSHOTGUN"] = {
        supressor = "COMPONENT_AT_AR_SUPP_02",
        flash = "COMPONENT_AT_AR_FLSH",
        grip = "COMPONENT_AT_AR_AFGRIP"
    },
    ["WEAPON_SNIPERRIFLE"] = {
        supressor = "COMPONENT_AT_AR_SUPP_02",
        clip = "COMPONENT_SNIPERRIFLE_CLIP_01",
        scope = "COMPONENT_AT_SCOPE_MAX",
        skin = "COMPONENT_SNIPERRIFLE_VARMOD_LUXE",
    },
    ["WEAPON_HEAVYSNIPER_MK2"] = {
        supressor = "COMPONENT_AT_SR_SUPP_03",
        clip = "COMPONENT_HEAVYSNIPER_MK2_CLIP_02",
        scope = "COMPONENT_AT_SCOPE_MAX",
        skin = "COMPONENT_HEAVYSNIPER_MK2_CAMO_04",
    },
}
